### ISSUE TITLE
Doesn't work with videos recorded from iPhone's camera

### ISSUE THREAD

**Issue by ArthurAlvarez** [TouSC/Video2LivePhoto#1]
Tried to use the demo project with the attached video and the result is in wrong orientation and unavailable to be used with motion on iOS 17 lock screen.

https://github.com/TouSC/Video2LivePhoto/assets/5571057/d3f8ff60-822a-4932-965f-8a4c1aa51b93

**Comment by TouSC** [comment]
It's works on my iPhone11 (17.0.1), although with a wrong orientation.
Try change the time value mentioned in this issue #2

**Comment by TouSC** [comment]
both problems fixed
