### ISSUE TITLE
Working with only Some Videos

### ISSUE THREAD

**Issue by Ankooo12** [TouSC/Video2LivePhoto#2]
### This is working with only some Videos in iOS 17. 

I have tried everything with various videos (Format, Dimensions, Duration). But I don't get it why it is not working with this video

![IMG_81968C0B5792-1](https://github.com/TouSC/Video2LivePhoto/assets/78063554/f27bc841-20c3-46fc-b1ce-69861718d292)

Video is here__________

https://github.com/TouSC/Video2LivePhoto/assets/78063554/3801e778-227e-4822-a1eb-8e853fa4c63a

**Comment by TouSC** [comment]
I tried your video. If you change the time passed to generateCGImagesAsynchronouslyForTimes from 0 to 0.5 it works. Hard to tell why and how to choose a proper cover image, since we don't know the logic behind iOS wallpaper.

**Comment by Ankooo12** [comment]
@TouSC  I appreciate your efforts. It is perfect. With this video, everything is working fine but I have tried with another video, and it has not worked. I have changed the dimensions and duration of the video but it does not work. Cna we make it work with every video?  Please check it.

https://github.com/TouSC/Video2LivePhoto/assets/78063554/761de0c6-bb72-4570-803e-d0ba027833a5

https://github.com/TouSC/Video2LivePhoto/assets/78063554/3f841ca4-81a9-4ce7-b84c-e3ad66d7b8c6



Thank you so much for your attention and participation.

**Comment by TouSC** [comment]
you can't change those two parameters, those are related to the metadata info in metadata.mov file.
instead, change the time value in this line:
`CMTime time = CMTimeMakeWithSeconds(0, asset.duration.timescale);`
for example in your given video, change the time from 0 to 0.5 works perfect in my iPhone

**Comment by TouSC** [comment]
I found mostly 0.5 will work better, just guessing: the iPhone wallpaper will play the frames between %40 - %50 of the video then ended up with the cover image with some transform, if the transform failed, then it won't enable motion mode.
