### ISSUE TITLE
Increase duration more than 1s

### ISSUE THREAD

**Issue by THDGunner** [TouSC/Video2LivePhoto#3]
I tried this project and found it very useful. But how can i Increase live photo duration to 3s ？
I look forward to your reply.

**Comment by TouSC** [comment]
If you just want a live photo (not workable as wallpaper), you can just jump over all the video processings, so there's no limit of duration. On the other hand, longer Live Photo as wallpaper is meaningless, since iOS wallpaper just trim a very short time of your livephoto.

**Comment by THDGunner** [comment]
> If you just want a live photo (not workable as wallpaper), you can just jump over all the video processings, so there's no limit of duration. On the other hand, longer Live Photo as wallpaper is meaningless, since iOS wallpaper just trim a very short time of your livephoto.

Thanks for your reply. I just want the exported live photo to look more complete. I increased the livePhotoDuration to CMTimeMake(1800, 600) and found that it can work normally.

**Comment by TouSC** [comment]
> > If you just want a live photo (not workable as wallpaper), you can just jump over all the video processings, so there's no limit of duration. On the other hand, longer Live Photo as wallpaper is meaningless, since iOS wallpaper just trim a very short time of your livephoto.
> 
> Thanks for your reply. I just want the exported live photo to look more complete. I increased the livePhotoDuration to CMTimeMake(1800, 600) and found that it can work normally.

Yes, save video as Live Photo is easy, just keep the video and the picture with the same identifier. All other efforts are for wallpaper.
